<a href="https://colab.research.google.com/github/ydgbii/week4_pytorch/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab: PyTorch Fundamentals

This notebook has two parts.

| Part | What you do |
| ----- | ----- |
| **Part A: Introduction to PyTorch** | Read and run the cells. Nothing to submit. |
| **Part B: Exercises** | 10 practical exercises, 10 marks each. |


**How to use this notebook:** run the cells from top to bottom (`Shift + Enter`). In Google Colab you can switch on a GPU with *Runtime -> Change runtime type -> GPU* (optional, everything also works on CPU).

---
# Part A: Introduction to PyTorch

[PyTorch](https://pytorch.org/) is an open source deep learning framework. It lets you store data as **tensors**, do fast maths on them (on CPU or GPU), and build neural networks.

In this part we cover only what you need most:

| Section | Topic |
| ----- | ----- |
| 1 | Importing PyTorch |
| 2 | What is a tensor? (scalar, vector, matrix, tensor) |
| 3 | Creating tensors (random, zeros, ones, ranges) |
| 4 | Tensor datatypes |
| 5 | Getting information from a tensor (shape, dtype, device) |
| 6 | Tensor operations and matrix multiplication |
| 7 | Aggregation (min, max, mean, sum) |
| 8 | Changing the shape of a tensor |
| 9 | Indexing |
| 10 | PyTorch and NumPy |
| 11 | Reproducibility (random seed) |
| 12 | Running tensors on a GPU |

## 1. Importing PyTorch

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu130


Tensors are the fundamental building block of machine learning.

Their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape `[3, 224, 224]` which would mean `[colour_channels, height, width]`, as in the image has `3` colour channels (red, green, blue), a height of `224` pixels and a width of `224` pixels.

![example of going from an input image to a tensor representation of the image, image gets broken down into 3 colour channels as well as numbers to represent the height and width](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)

In tensor-speak (the language used to describe tensors), the tensor would have three dimensions, one for `colour_channels`, `height` and `width`.

But we're getting ahead of ourselves.

Let's learn more about tensors by coding them.

## 2. What is a tensor?

A **tensor** is a container of numbers. It is the basic building block of deep learning: images, text, audio and tables are all turned into tensors before a model can use them.

For example, a colour image can be stored as a tensor of shape `[3, 224, 224]`, meaning `[colour_channels, height, width]`.

Tensors come in different numbers of dimensions:

| Name | What is it? | Number of dimensions (`ndim`) |
| ----- | ----- | ----- |
| **scalar** | a single number | 0 |
| **vector** | a list of numbers | 1 |
| **matrix** | a table of numbers (rows and columns) | 2 |
| **tensor** | numbers arranged in any number of dimensions | 0, 1, 2, 3, ... |

![scalar vector matrix tensor and what they look like](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

Two attributes describe every tensor:
* `ndim` - how many dimensions it has
* `shape` - how many elements there are along each dimension

In [ ]:
# Scalar: a single number, 0 dimensions
scalar = torch.tensor(7)
print(scalar)
print("ndim: ", scalar.ndim)
print("shape:", scalar.shape)
print("as a Python number:", scalar.item())   # .item() only works on one-element tensors

tensor(7)
ndim:  0
shape: torch.Size([])
as a Python number: 7


In [ ]:
# Vector: 1 dimension
vector = torch.tensor([7, 7])
print(vector)
print("ndim: ", vector.ndim)
print("shape:", vector.shape)

tensor([7, 7])
ndim:  1
shape: torch.Size([2])


In [ ]:
# Matrix: 2 dimensions (rows, columns)
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)
print("ndim: ", MATRIX.ndim)
print("shape:", MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
ndim:  2
shape: torch.Size([2, 2])


In [ ]:
# Tensor: 3 dimensions here
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
print(TENSOR)
print("ndim: ", TENSOR.ndim)
print("shape:", TENSOR.shape)   # 1 block of 3 rows and 3 columns

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
ndim:  3
shape: torch.Size([1, 3, 3])


**Tip:** the number of dimensions equals the number of opening square brackets `[` at the start of the tensor. `[[[` means 3 dimensions.

The shape is read from the outside in: `torch.Size([1, 3, 3])` means 1 block, each with 3 rows, each with 3 values.

## 3. Creating tensors

You will rarely type tensors by hand. A neural network starts with tensors full of **random numbers** and then adjusts them as it learns:

`start with random numbers -> look at data -> update the numbers -> look at data -> update the numbers ...`

The most useful functions for creating tensors are:

| Function | What it creates |
| ----- | ----- |
| `torch.rand(size)` | random numbers between 0 and 1 |
| `torch.zeros(size)` | all zeros |
| `torch.ones(size)` | all ones |
| `torch.arange(start, end, step)` | a range of numbers (`end` is not included) |
| `torch.zeros_like(x)`, `torch.ones_like(x)` | zeros or ones with the same shape as `x` |

In [ ]:
# Random tensor with 3 rows and 4 columns
random_tensor = torch.rand(size=(3, 4))
print(random_tensor)

# Random tensor in the shape of an image: [colour_channels, height, width]
random_image = torch.rand(size=(3, 224, 224))
print(random_image.shape, random_image.ndim)

tensor([[0.4867, 0.6243, 0.1512, 0.9278],
        [0.2699, 0.9344, 0.8318, 0.8281],
        [0.1773, 0.0520, 0.8974, 0.0311]])
torch.Size([3, 224, 224]) 3


In [ ]:
# Zeros and ones
zeros = torch.zeros(size=(3, 4))
ones = torch.ones(size=(3, 4))
print(zeros)
print(ones)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
# A range of numbers: start=0, end=10 (not included), step=1
zero_to_nine = torch.arange(start=0, end=10, step=1)
print(zero_to_nine)

# Zeros with the same shape as another tensor
print(torch.zeros_like(zero_to_nine))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


## 4. Tensor datatypes

Every tensor has a datatype (`dtype`). The ones you will meet most often:

| dtype | Meaning | When you see it |
| ----- | ----- | ----- |
| `torch.float32` | decimal numbers, 32 bits | the default for decimal values, used by most models |
| `torch.int64` | whole numbers, 64 bits | the default for whole numbers, used for labels and indexes |
| `torch.float16` | decimal numbers, 16 bits | smaller and faster, but less precise |

You choose the datatype with the `dtype` parameter, and you change it later with `.type()`.

In [ ]:
# Decimal values give float32 by default
float_32_tensor = torch.tensor([3.0, 6.0, 9.0])
print(float_32_tensor.dtype)

# Whole numbers give int64 by default
int_tensor = torch.tensor([3, 6, 9])
print(int_tensor.dtype)

# Choose the datatype when creating the tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
print(float_16_tensor.dtype)

# Change the datatype of an existing tensor
converted = int_tensor.type(torch.float32)
print(converted, converted.dtype)

torch.float32
torch.int64
torch.float16
tensor([3., 6., 9.]) torch.float32


## 5. Getting information from a tensor

Most PyTorch errors come from one of three things. When something breaks, check them in this order:

* `shape` - **what shape** is the tensor?
* `dtype` - **what datatype** is it?
* `device` - **where** is it stored (CPU or GPU)?

In [ ]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")   # CPU by default

tensor([[0.4127, 0.4261, 0.0216, 0.4080],
        [0.6008, 0.6966, 0.6181, 0.5216],
        [0.0052, 0.3610, 0.5668, 0.4065]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## 6. Tensor operations

A neural network is built from a small set of operations on tensors: addition, subtraction, multiplication, division and **matrix multiplication**.

### 6.1 Basic operations

These work element by element.

In [ ]:
tensor = torch.tensor([1, 2, 3])

print(tensor + 10)   # add 10 to every element
print(tensor - 10)   # subtract 10 from every element
print(tensor * 10)   # multiply every element by 10
print(tensor / 10)   # divide every element by 10

# The original tensor does not change unless you reassign it
print(tensor)
tensor = tensor + 10
print(tensor)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])
tensor([1, 2, 3])
tensor([11, 12, 13])


### 6.2 Element-wise multiplication vs matrix multiplication

For a tensor with values `[1, 2, 3]`:

| Operation | Calculation | Code |
| ----- | ----- | ----- |
| **Element-wise multiplication** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensor * tensor` |
| **Matrix multiplication** | `1*1 + 2*2 + 3*3` = `14` | `torch.matmul(tensor, tensor)` or `tensor @ tensor` |

In [ ]:
tensor = torch.tensor([1, 2, 3])

print("Element-wise:", tensor * tensor)
print("Matrix multiplication:", torch.matmul(tensor, tensor))
print("Matrix multiplication with @:", tensor @ tensor)

Element-wise: tensor([1, 4, 9])
Matrix multiplication: tensor(14)
Matrix multiplication with @: tensor(14)


### 6.3 The two rules of matrix multiplication

1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` will not work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
2. The result has the shape of the **outer dimensions**:
  * `(2, 3) @ (3, 2)` -> `(2, 2)`
  * `(3, 2) @ (2, 3)` -> `(3, 3)`

Breaking rule 1 gives a **shape error**, one of the most common errors in deep learning.

In [ ]:
tensor_A = torch.tensor([[1., 2.],
                         [3., 4.],
                         [5., 6.]])     # shape (3, 2)

tensor_B = torch.tensor([[7., 10.],
                         [8., 11.],
                         [9., 12.]])    # shape (3, 2)

# (3, 2) @ (3, 2): the inner dimensions 2 and 3 do not match, so this fails
try:
    torch.matmul(tensor_A, tensor_B)
except RuntimeError as error:
    print("Error:", error)

Error: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


To fix it, **transpose** one of the tensors with `.T`. Transposing swaps rows and columns, so a `(3, 2)` tensor becomes `(2, 3)`.

In [ ]:
print("tensor_B shape:  ", tensor_B.shape)
print("tensor_B.T shape:", tensor_B.T.shape)

# (3, 2) @ (2, 3): the inner dimensions match, the result is (3, 3)
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print("Output shape:", output.shape)

tensor_B shape:   torch.Size([3, 2])
tensor_B.T shape: torch.Size([2, 3])
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
Output shape: torch.Size([3, 3])


## 7. Aggregation (min, max, mean, sum)

Aggregation turns many values into fewer values.

`argmin()` and `argmax()` return the **position (index)** of the smallest and largest value, not the value itself.

In [ ]:
x = torch.arange(0, 100, 10)
print(x)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Sum: {x.sum()}")

# mean() needs a float tensor, so convert the datatype first
print(f"Mean: {x.type(torch.float32).mean()}")

print(f"Index of the minimum value: {x.argmin()}")
print(f"Index of the maximum value: {x.argmax()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Sum: 450
Mean: 45.0
Index of the minimum value: 0
Index of the maximum value: 9


## 8. Changing the shape of a tensor

Models need tensors in the right shape. These methods change the shape without changing the values:

| Method | What it does |
| ----- | ----- |
| `x.reshape(shape)` | gives `x` a new shape (the total number of elements must stay the same) |
| `torch.stack([a, b], dim)` | joins tensors along a **new** dimension |
| `x.squeeze()` | removes all dimensions of size 1 |
| `x.unsqueeze(dim)` | adds a dimension of size 1 at position `dim` |
| `x.permute(dims)` | rearranges the order of the dimensions |

In [ ]:
x = torch.arange(1., 9.)
print(x, x.shape)

# reshape: 8 elements can become 2 rows of 4
x_reshaped = x.reshape(2, 4)
print(x_reshaped, x_reshaped.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8.]) torch.Size([8])
tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]]) torch.Size([2, 4])


In [ ]:
# stack: join tensors along a new dimension
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(torch.stack([a, b], dim=0))   # a and b become rows,    shape (2, 3)
print(torch.stack([a, b], dim=1))   # a and b become columns, shape (3, 2)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
# squeeze: remove dimensions of size 1
y = torch.rand(1, 5)
y_squeezed = y.squeeze()
print("Before squeeze:", y.shape)
print("After squeeze: ", y_squeezed.shape)

# unsqueeze: add a dimension of size 1
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
print("After unsqueeze(dim=0):", y_unsqueezed.shape)

Before squeeze: torch.Size([1, 5])
After squeeze:  torch.Size([5])
After unsqueeze(dim=0): torch.Size([1, 5])


In [ ]:
# permute: rearrange the dimensions
# Example: an image stored as [height, width, colour_channels]
image = torch.rand(size=(224, 224, 3))

# PyTorch models expect [colour_channels, height, width]
image_permuted = image.permute(2, 0, 1)   # old dimension 2 goes first, then 0, then 1

print("Before permute:", image.shape)
print("After permute: ", image_permuted.shape)

Before permute: torch.Size([224, 224, 3])
After permute:  torch.Size([3, 224, 224])


## 9. Indexing (selecting data from tensors)

Indexing works like Python lists and NumPy arrays. You index from the outer dimension to the inner dimension. Use `:` to mean "everything in this dimension".

`torch.Size([1, 3, 3])`.

The dimensions go outer to inner.

That means there's 1 dimension of 3 by 3.

![example of different tensor dimensions](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)

> **Note:** You might've noticed me using lowercase letters for `scalar` and `vector` and uppercase letters for `MATRIX` and `TENSOR`. This was on purpose. In practice, you'll often see scalars and vectors denoted as lowercase letters such as `y` or `a`. And matrices and tensors denoted as uppercase letters such as `X` or `W`.
>
> You also might notice the names martrix and tensor used interchangably. This is common. Since in PyTorch you're often dealing with `torch.Tensor`s (hence the tensor name), however, the shape and dimensions of what's inside will dictate what it actually is.


In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x, x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])


In [ ]:
print(x[0])          # the first (and only) block: a 3x3 matrix
print(x[0][0])       # the first row of that block
print(x[0][0][0])    # the first value of that row

# The same thing with commas
print(x[0, 1, 1])    # block 0, row 1, column 1 -> 5
print(x[0, 1, :])    # block 0, row 1, all columns -> [4, 5, 6]
print(x[0, :, 1])    # block 0, all rows, column 1 -> [2, 5, 8]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor(5)
tensor([4, 5, 6])
tensor([2, 5, 8])


## 10. PyTorch and NumPy

Data often arrives as a NumPy array, and plotting libraries expect NumPy arrays, so you need to convert in both directions:

* `torch.from_numpy(array)` - NumPy array -> PyTorch tensor
* `tensor.numpy()` - PyTorch tensor -> NumPy array

Note: NumPy uses `float64` by default while PyTorch uses `float32`. The conversion keeps the original datatype.

In [ ]:
import numpy as np

# NumPy array -> tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(array, array.dtype)
print(tensor)

# Convert to float32 if you need the PyTorch default
print(tensor.type(torch.float32).dtype)

# Tensor -> NumPy array
tensor = torch.ones(7)
numpy_array = tensor.numpy()
print(numpy_array, numpy_array.dtype)

[1. 2. 3. 4. 5. 6. 7.] float64
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
torch.float32
[1. 1. 1. 1. 1. 1. 1.] float32


## 11. Reproducibility (random seed)

`torch.rand()` gives different numbers every time. That makes experiments hard to repeat.

`torch.manual_seed(seed)` fixes the starting point of the random number generator, so the same seed always gives the same "random" numbers.

Important: call `torch.manual_seed()` again before **each** random call that you want to repeat.

In [ ]:
# Without a seed: two different tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A == random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# With a seed: two identical tensors
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)    # set the seed again before the second call
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## 12. Running tensors on a GPU

A GPU does the maths of neural networks (mainly matrix multiplication) much faster than a CPU.

The standard pattern is **device-agnostic code**: use the GPU if there is one, otherwise use the CPU. The same code then runs on any computer.

In [ ]:
# Is a GPU available?
print(torch.cuda.is_available())

# Device-agnostic setup
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

True
cuda


Move a tensor to a device with `.to(device)`. This returns a copy, so reassign it if you want to keep the result.

Two tensors must be on the **same device** before you can combine them.

In [ ]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor_on_device = tensor.to(device)
print(tensor_on_device, tensor_on_device.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0


NumPy only works on the CPU. Calling `.numpy()` on a GPU tensor gives an error, so bring the tensor back with `.cpu()` first.

In [ ]:
tensor_back_on_cpu = tensor_on_device.cpu().numpy()
print(tensor_back_on_cpu)

[1 2 3]


Remember, matrix multiplication is all you need!

![matrix multiplication is all you need](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00_matrix_multiplication_is_all_you_need.jpeg)

*When you start digging into neural network layers and building your own, you'll find matrix multiplications everywhere. **Source:** https://marksaroufim.substack.com/p/working-class-deep-learner*

---
# Part B: Exercises (100 marks)

**Instructions**

1. Replace every `None` with your own code. Do not rename the variables.
2. After each exercise, run the **Check** cell below it. It shows which sub-parts are correct and your marks for that exercise.
3. Do not edit the Check cells.
4. When you finish, run the last cell of the notebook to see your total out of 100.

| Exercise | Topic | Marks |
| ----- | ----- | ----- |
| 1 | Creating tensors | 10 |
| 2 | Random tensors, zeros, ones and ranges | 10 |
| 3 | Datatypes and tensor information | 10 |
| 4 | Basic operations | 10 |
| 5 | Matrix multiplication | 10 |
| 6 | Aggregation | 10 |
| 7 | Reshaping and stacking | 10 |
| 8 | Squeeze, unsqueeze and permute | 10 |
| 9 | Indexing and NumPy | 10 |
| 10 | Reproducibility and GPU | 10 |
| | **Total** | **100** |

Run the next cell once before you start.

In [ ]:
# Setup for the exercises - run this cell once, do not edit
import torch
import numpy as np

SCORES = {}


def same(a, b):
    """True if a is a tensor with the same shape and the same values as b."""
    b = torch.as_tensor(b)
    return (isinstance(a, torch.Tensor)
            and a.shape == b.shape
            and torch.allclose(a.detach().cpu().double(), b.detach().cpu().double()))


def grade(exercise, checks):
    """Run the checks for one exercise and print the marks."""
    earned = 0
    total = 0
    print(f"Exercise {exercise}")
    for description, marks, test in checks:
        total += marks
        try:
            passed = bool(test())
        except Exception:
            passed = False
        if passed:
            earned += marks
        result = "PASS" if passed else "FAIL"
        print(f"  [{result}] {description}: {marks if passed else 0}/{marks}")
    SCORES[exercise] = earned
    print(f"  Marks for exercise {exercise}: {earned}/{total}")

## Exercise 1: Creating tensors (10 marks)

In [52]:
# (a) Create a scalar tensor with the value 42                                  [2 marks]
scalar = torch.tensor(42)
print(scalar)
print("ndim: ", scalar.ndim)
print("shape:", scalar.shape)

# (b) Create a vector tensor with the values [1, 2, 3, 4]                       [2 marks]
vector = torch.tensor([1,2,3,4])
print(vector)
print("ndim: ",vector.ndim)
print("shape:", vector.shape)

# (c) Create a 2x3 matrix tensor with the values [[1, 2, 3], [4, 5, 6]]         [3 marks]
matrix = torch.tensor([[1,2,3],[4,5,6]])
print(matrix)
print("ndim: ", matrix.ndim)
print("shape:", matrix.shape)

# (d) Create a tensor of shape (2, 2, 2) holding the values 1 to 8,
#     using torch.arange and reshape                                            [3 marks]
tensor_3d =torch.arange(1,9).reshape(2,2,2)
print(tensor_3d)
print("ndim: ", tensor_3d.ndim)
print("shape:", tensor_3d.shape)


for name, t in [("scalar", scalar), ("vector", vector), ("matrix", matrix), ("tensor_3d", tensor_3d)]:
    if t is not None:
        print(f"{name}: ndim = {t.ndim}, shape = {t.shape}")

tensor(42)
ndim:  0
shape: torch.Size([])
tensor([1, 2, 3, 4])
ndim:  1
shape: torch.Size([4])
tensor([[1, 2, 3],
        [4, 5, 6]])
ndim:  2
shape: torch.Size([2, 3])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
ndim:  3
shape: torch.Size([2, 2, 2])
scalar: ndim = 0, shape = torch.Size([])
vector: ndim = 1, shape = torch.Size([4])
matrix: ndim = 2, shape = torch.Size([2, 3])
tensor_3d: ndim = 3, shape = torch.Size([2, 2, 2])


In [54]:
# Check - do not edit
grade(1, [
    ("(a) scalar with value 42", 2, lambda: scalar.ndim == 0 and scalar.item() == 42),
    ("(b) vector [1, 2, 3, 4]", 2, lambda: same(vector, [1, 2, 3, 4])),
    ("(c) 2x3 matrix", 3, lambda: same(matrix, [[1, 2, 3], [4, 5, 6]])),
    ("(d) 3D tensor of shape (2, 2, 2) with values 1 to 8", 3,
     lambda: same(tensor_3d, torch.arange(1, 9).reshape(2, 2, 2))),
])

Exercise 1
  [PASS] (a) scalar with value 42: 2/2
  [PASS] (b) vector [1, 2, 3, 4]: 2/2
  [PASS] (c) 2x3 matrix: 3/3
  [PASS] (d) 3D tensor of shape (2, 2, 2) with values 1 to 8: 3/3
  Marks for exercise 1: 10/10


## Exercise 2: Random tensors, zeros, ones and ranges (10 marks)

In [55]:
# (a) Create a random tensor of shape (4, 4)                                    [2 marks]
random_tensor= torch.rand(4,4)
print(random_tensor)


# (b) Create a random tensor in the shape of an image:
#     (3, 224, 224) = (colour_channels, height, width)                          [2 marks]
image_tensor = torch.rand(3,224,224)
print(image_tensor)

# (c) Create a tensor of zeros with shape (5, 5)                                [2 marks]
zeros = torch.zeros(5,5)
print(zeros)

# (d) Create a tensor of ones with the same shape as base_tensor,
#     using torch.ones_like                                                     [2 marks]
base_tensor = torch.rand(3, 3)
ones_like_tensor = torch.ones_like(base_tensor)
print(ones_like_tensor)

# (e) Create the tensor [0, 2, 4, ..., 20] using torch.arange
#     (20 must be included)                                                     [2 marks]
range_tensor = torch.arange(0,21,2)
print(range_tensor)

tensor([[0.9503, 0.2564, 0.6645, 0.8609],
        [0.3538, 0.3347, 0.7285, 0.5794],
        [0.4946, 0.9831, 0.5134, 0.2580],
        [0.5002, 0.6152, 0.6283, 0.6972]])
tensor([[[5.4195e-01, 5.6509e-01, 8.9124e-02,  ..., 8.8072e-01,
          8.8718e-01, 2.2416e-01],
         [2.9946e-01, 1.8773e-01, 9.6593e-01,  ..., 1.8426e-01,
          1.2439e-01, 7.1970e-01],
         [9.8056e-01, 9.0397e-01, 2.3475e-01,  ..., 4.3863e-01,
          5.5270e-01, 2.9400e-01],
         ...,
         [4.6090e-02, 4.4483e-01, 3.0630e-01,  ..., 5.9756e-01,
          6.0668e-01, 1.0329e-01],
         [9.8780e-01, 7.7827e-01, 9.2600e-01,  ..., 2.7893e-01,
          4.1446e-01, 3.7746e-02],
         [8.5133e-01, 6.6108e-01, 2.3627e-01,  ..., 3.4278e-01,
          7.9751e-01, 1.6961e-01]],

        [[3.1866e-01, 3.2776e-01, 3.2779e-01,  ..., 8.8292e-01,
          6.6746e-01, 9.2817e-01],
         [5.9622e-01, 4.5426e-02, 1.9009e-01,  ..., 4.8296e-01,
          2.1832e-01, 3.5920e-01],
         [2.8143e-01, 2

In [56]:
# Check - do not edit
grade(2, [
    ("(a) random tensor of shape (4, 4)", 2,
     lambda: random_tensor.shape == (4, 4) and random_tensor.is_floating_point()),
    ("(b) image tensor of shape (3, 224, 224)", 2,
     lambda: image_tensor.shape == (3, 224, 224) and image_tensor.is_floating_point()),
    ("(c) zeros of shape (5, 5)", 2, lambda: same(zeros, torch.zeros(5, 5))),
    ("(d) ones with the shape of base_tensor", 2, lambda: same(ones_like_tensor, torch.ones(3, 3))),
    ("(e) range 0 to 20 with step 2", 2, lambda: same(range_tensor, torch.arange(0, 21, 2))),
])

Exercise 2
  [PASS] (a) random tensor of shape (4, 4): 2/2
  [PASS] (b) image tensor of shape (3, 224, 224): 2/2
  [PASS] (c) zeros of shape (5, 5): 2/2
  [PASS] (d) ones with the shape of base_tensor: 2/2
  [PASS] (e) range 0 to 20 with step 2: 2/2
  Marks for exercise 2: 10/10


## Exercise 3: Datatypes and tensor information (10 marks)

In [61]:
# (a) Create a tensor with the values [1.0, 2.0, 3.0] and dtype torch.float16   [3 marks]
float16_tensor = torch.tensor([1.0,2.0,3.0],dtype=torch.float16)
print(float16_tensor.dtype)

# (b) Convert float16_tensor to torch.float32                                   [3 marks]
float32_tensor = torch.tensor(float16_tensor,dtype=torch.float32 )
print(float32_tensor.dtype)

# (c) Create a random tensor of shape (2, 3, 4)                                 [1 mark]
info_tensor = torch.rand(2,3,4)
print(info_tensor)

# (d) Store its shape, datatype and device in these three variables             [3 marks]
info_shape = info_tensor.shape
info_dtype = info_tensor.dtype
info_device = info_tensor.device

print(f"Shape: {info_shape}")
print(f"Datatype: {info_dtype}")
print(f"Device: {info_device}")

torch.float16
torch.float32
tensor([[[0.4267, 0.1712, 0.7690, 0.7061],
         [0.5195, 0.8164, 0.2239, 0.9910],
         [0.8820, 0.4774, 0.6358, 0.5167]],

        [[0.2789, 0.5498, 0.5647, 0.4838],
         [0.2620, 0.9833, 0.5152, 0.3571],
         [0.3119, 0.5281, 0.2620, 0.4675]]])
Shape: torch.Size([2, 3, 4])
Datatype: torch.float32
Device: cpu


/tmp/ipykernel_3099/3248182927.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  float32_tensor = torch.tensor(float16_tensor,dtype=torch.float32 )


In [62]:
# Check - do not edit
grade(3, [
    ("(a) float16 tensor [1.0, 2.0, 3.0]", 3,
     lambda: float16_tensor.dtype == torch.float16 and same(float16_tensor, [1.0, 2.0, 3.0])),
    ("(b) converted to float32", 3,
     lambda: float32_tensor.dtype == torch.float32 and same(float32_tensor, [1.0, 2.0, 3.0])),
    ("(c) random tensor of shape (2, 3, 4)", 1, lambda: info_tensor.shape == (2, 3, 4)),
    ("(d) shape stored in info_shape", 1,
     lambda: info_shape is not None and tuple(info_shape) == (2, 3, 4)),
    ("(d) datatype stored in info_dtype", 1,
     lambda: isinstance(info_dtype, torch.dtype) and info_dtype == info_tensor.dtype),
    ("(d) device stored in info_device", 1,
     lambda: info_device is not None and str(info_device) == str(info_tensor.device)),
])

Exercise 3
  [PASS] (a) float16 tensor [1.0, 2.0, 3.0]: 3/3
  [PASS] (b) converted to float32: 3/3
  [PASS] (c) random tensor of shape (2, 3, 4): 1/1
  [PASS] (d) shape stored in info_shape: 1/1
  [PASS] (d) datatype stored in info_dtype: 1/1
  [PASS] (d) device stored in info_device: 1/1
  Marks for exercise 3: 10/10


## Exercise 4: Basic operations (10 marks)

In [68]:
tensor = torch.tensor([10, 20, 30])

# (a) Add 5 to every element                                                    [2 marks]
added = tensor+5
print("Added:", added)

# (b) Subtract 10 from every element                                            [2 marks]
subtracted = tensor-10
print("Subtracted:", subtracted)

# (c) Multiply every element by 2                                               [3 marks]
multiplied = tensor*2
print("Multiplied:", multiplied)

# (d) Divide every element by 10                                                [3 marks]
divided = tensor/10
print("Divided:",divided )


Added: tensor([15, 25, 35])
Subtracted: tensor([ 0, 10, 20])
Multiplied: tensor([20, 40, 60])
Divided: tensor([1., 2., 3.])


In [69]:
# Check - do not edit
grade(4, [
    ("(a) add 5", 2, lambda: same(added, [15, 25, 35])),
    ("(b) subtract 10", 2, lambda: same(subtracted, [0, 10, 20])),
    ("(c) multiply by 2", 3, lambda: same(multiplied, [20, 40, 60])),
    ("(d) divide by 10", 3, lambda: same(divided, [1, 2, 3])),
])

Exercise 4
  [PASS] (a) add 5: 2/2
  [PASS] (b) subtract 10: 2/2
  [PASS] (c) multiply by 2: 3/3
  [PASS] (d) divide by 10: 3/3
  Marks for exercise 4: 10/10


## Exercise 5: Matrix multiplication (10 marks)

In [72]:
torch.manual_seed(0)
A = torch.rand(2, 3)
B = torch.rand(3, 2)

# (a) Matrix-multiply A and B                                                   [4 marks]
result_AB = torch.matmul(A,B)

C = torch.tensor([[1., 2.],
                  [3., 4.],
                  [5., 6.]])      # shape (3, 2)

D = torch.tensor([[7., 10.],
                  [8., 11.],
                  [9., 12.]])     # shape (3, 2)

# (b) C and D cannot be matrix-multiplied as they are (shape error).
#     Fix the shapes with a transpose so that the result has shape (3, 3)       [6 marks]
result_CD= torch.matmul(C,D.T)

print(result_AB)
print(result_CD)

tensor([[0.6241, 0.9662],
        [0.4260, 0.5675]])
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [73]:
# Check - do not edit
grade(5, [
    ("(a) A matrix-multiplied by B, shape (2, 2)", 4, lambda: same(result_AB, A @ B)),
    ("(b) C and D multiplied after a transpose, shape (3, 3)", 6, lambda: same(result_CD, C @ D.T)),
])

Exercise 5
  [PASS] (a) A matrix-multiplied by B, shape (2, 2): 4/4
  [PASS] (b) C and D multiplied after a transpose, shape (3, 3): 6/6
  Marks for exercise 5: 10/10


## Exercise 6: Aggregation (10 marks)

In [75]:
agg_tensor = torch.arange(0, 101)    # the values 0, 1, 2, ..., 100

# (a) Minimum value                                                             [2 marks]
min_value = min(agg_tensor)

# (b) Maximum value                                                             [2 marks]
max_value = max(agg_tensor)

# (c) Mean value (hint: mean() needs a float tensor)                            [2 marks]
mean_value = torch.mean(agg_tensor.type(torch.float32))

# (d) Sum of all values                                                         [2 marks]
sum_value = torch.sum(agg_tensor)

# (e) Index (position) of the minimum value                                     [1 mark]
min_index = torch.argmin(agg_tensor)

# (f) Index (position) of the maximum value                                     [1 mark]
max_index = torch.argmax(agg_tensor)

print(min_value, max_value, mean_value, sum_value, min_index, max_index)

tensor(0) tensor(100) tensor(50.) tensor(5050) tensor(0) tensor(100)


In [76]:
# Check - do not edit
grade(6, [
    ("(a) minimum", 2, lambda: float(min_value) == 0),
    ("(b) maximum", 2, lambda: float(max_value) == 100),
    ("(c) mean", 2, lambda: abs(float(mean_value) - 50.0) < 1e-4),
    ("(d) sum", 2, lambda: float(sum_value) == 5050),
    ("(e) index of the minimum", 1, lambda: int(min_index) == 0),
    ("(f) index of the maximum", 1, lambda: int(max_index) == 100),
])

Exercise 6
  [PASS] (a) minimum: 2/2
  [PASS] (b) maximum: 2/2
  [PASS] (c) mean: 2/2
  [PASS] (d) sum: 2/2
  [PASS] (e) index of the minimum: 1/1
  [PASS] (f) index of the maximum: 1/1
  Marks for exercise 6: 10/10


## Exercise 7: Reshaping and stacking (10 marks)

In [77]:
reshape_tensor = torch.arange(10)    # shape (10,)

# (a) Reshape reshape_tensor to shape (2, 5)                                    [4 marks]
reshaped = reshape_tensor.reshape(2,5)

tensor1 = torch.tensor([[1, 2],
                        [3, 4]])
tensor2 = torch.tensor([[5, 6],
                        [7, 8]])

# (b) Stack tensor1 and tensor2 along dim=0 using torch.stack                   [3 marks]
stacked_dim0 = torch.stack([tensor1,tensor2],dim=0)

# (c) Stack tensor1 and tensor2 along dim=1 using torch.stack                   [3 marks]
stacked_dim1 = torch.stack([tensor1,tensor2],dim=1)


print(reshaped)
print(stacked_dim0)
print(stacked_dim1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


In [78]:
# Check - do not edit
grade(7, [
    ("(a) reshaped to (2, 5)", 4, lambda: same(reshaped, torch.arange(10).reshape(2, 5))),
    ("(b) stacked along dim=0", 3, lambda: same(stacked_dim0, torch.stack([tensor1, tensor2], dim=0))),
    ("(c) stacked along dim=1", 3, lambda: same(stacked_dim1, torch.stack([tensor1, tensor2], dim=1))),
])

Exercise 7
  [PASS] (a) reshaped to (2, 5): 4/4
  [PASS] (b) stacked along dim=0: 3/3
  [PASS] (c) stacked along dim=1: 3/3
  Marks for exercise 7: 10/10


## Exercise 8: Squeeze, unsqueeze and permute (10 marks)

In [79]:
squeeze_tensor = torch.rand(1, 3, 1)

# (a) Remove all dimensions of size 1 from squeeze_tensor -> shape (3,)         [3 marks]
squeezed = squeeze_tensor.squeeze()

# (b) Add a dimension of size 1 at dim=0 to squeezed -> shape (1, 3)            [3 marks]
unsqueezed = squeezed.unsqueeze(dim=0)

image_chw = torch.rand(3, 100, 100)    # (colour_channels, height, width)

# (c) Rearrange image_chw to (height, width, colour_channels) = (100, 100, 3)   [4 marks]
permuted = image_chw.permute(1,2,0)

for name, t in [("squeezed", squeezed), ("unsqueezed", unsqueezed), ("permuted", permuted)]:
    if t is not None:
        print(f"{name}: shape = {t.shape}")

squeezed: shape = torch.Size([3])
unsqueezed: shape = torch.Size([1, 3])
permuted: shape = torch.Size([100, 100, 3])


In [80]:
# Check - do not edit
grade(8, [
    ("(a) squeezed to shape (3,)", 3, lambda: same(squeezed, squeeze_tensor.reshape(3))),
    ("(b) unsqueezed to shape (1, 3)", 3, lambda: same(unsqueezed, squeeze_tensor.reshape(1, 3))),
    ("(c) permuted to shape (100, 100, 3)", 4, lambda: same(permuted, image_chw.permute(1, 2, 0))),
])

Exercise 8
  [PASS] (a) squeezed to shape (3,): 3/3
  [PASS] (b) unsqueezed to shape (1, 3): 3/3
  [PASS] (c) permuted to shape (100, 100, 3): 4/4
  Marks for exercise 8: 10/10


## Exercise 9: Indexing and NumPy (10 marks)

In [81]:
index_tensor = torch.tensor([[[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]]])    # shape (1, 3, 3)

# (a) Use indexing to get the value 5                                           [2 marks]
five = index_tensor[0][1][1]

# (b) Use indexing to get the second row [4, 5, 6]                              [2 marks]
second_row = index_tensor[0][1]

# (c) Use indexing to get the last column [3, 6, 9]                             [2 marks]
last_column = index_tensor[0][:,2]

numpy_array = np.array([1, 2, 3, 4])

# (d) Convert numpy_array to a PyTorch tensor                                   [2 marks]
tensor_from_numpy = torch.from_numpy(numpy_array)

pytorch_tensor = torch.tensor([5, 6, 7, 8])

# (e) Convert pytorch_tensor to a NumPy array                                   [2 marks]
numpy_from_tensor = pytorch_tensor.numpy()


print(five, second_row, last_column)
print(tensor_from_numpy, numpy_from_tensor)

tensor(5) tensor([4, 5, 6]) tensor([3, 6, 9])
tensor([1, 2, 3, 4]) [5 6 7 8]


In [82]:
# Check - do not edit
grade(9, [
    ("(a) the value 5", 2, lambda: isinstance(five, torch.Tensor) and five.numel() == 1 and five.item() == 5),
    ("(b) the second row", 2, lambda: same(second_row.flatten(), [4, 5, 6])),
    ("(c) the last column", 2, lambda: same(last_column.flatten(), [3, 6, 9])),
    ("(d) NumPy array to tensor", 2, lambda: same(tensor_from_numpy, [1, 2, 3, 4])),
    ("(e) tensor to NumPy array", 2,
     lambda: isinstance(numpy_from_tensor, np.ndarray) and np.array_equal(numpy_from_tensor, [5, 6, 7, 8])),
])

Exercise 9
  [PASS] (a) the value 5: 2/2
  [PASS] (b) the second row: 2/2
  [PASS] (c) the last column: 2/2
  [PASS] (d) NumPy array to tensor: 2/2
  [PASS] (e) tensor to NumPy array: 2/2
  Marks for exercise 9: 10/10


## Exercise 10: Reproducibility and GPU (10 marks)

In [99]:
# (a) Use the seed 77 to create two random tensors of shape (2, 2)
#     that are exactly equal. Remember to set the seed before each one.         [4 marks]
RANDOM_SEED = 77

torch.manual_seed(RANDOM_SEED)
rand1 = torch.rand(2, 2)

torch.manual_seed(RANDOM_SEED)  # set the seed again before the second call
rand2 = torch.rand(2, 2)

print(torch.equal(rand1, rand2))


# (b) Set device to "cuda" if a GPU is available, otherwise "cpu"               [2 marks]
device = "cuda" if torch.cuda.is_available() else "cpu"

my_tensor = torch.tensor([10, 20, 30])

# (c) Move my_tensor to device                                                  [2 marks]
tensor_on_device = my_tensor.to(device)

# (d) Bring tensor_on_device back to the CPU and convert it to a NumPy array    [2 marks]
cpu_numpy = tensor_on_device.cpu().numpy()
print(device)

print(rand1)
print(rand2)
print(device, tensor_on_device, cpu_numpy)

True
cuda
tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])
tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])
cuda tensor([10, 20, 30], device='cuda:0') [10 20 30]


In [100]:
# Check - do not edit
def _seeded():
    torch.manual_seed(77)
    return torch.rand(2, 2)

_expected_device = "cuda" if torch.cuda.is_available() else "cpu"

grade(10, [
    ("(a) two equal random tensors from seed 77", 4,
     lambda: same(rand1, _seeded()) and same(rand2, _seeded())),
    ("(b) device chosen correctly", 2,
     lambda: device is not None and str(device).split(":")[0] == _expected_device),
    ("(c) tensor moved to device", 2,
     lambda: tensor_on_device.device.type == _expected_device and same(tensor_on_device, [10, 20, 30])),
    ("(d) back on the CPU as a NumPy array", 2,
     lambda: isinstance(cpu_numpy, np.ndarray) and np.array_equal(cpu_numpy, [10, 20, 30])),
])

Exercise 10
  [PASS] (a) two equal random tensors from seed 77: 4/4
  [PASS] (b) device chosen correctly: 2/2
  [PASS] (c) tensor moved to device: 2/2
  [PASS] (d) back on the CPU as a NumPy array: 2/2
  Marks for exercise 10: 10/10


---
## Total marks

Run this cell after you have run all ten Check cells.

In [101]:
# Total - do not edit
print("Exercise   Marks")
total = 0
for exercise in range(1, 11):
    marks = SCORES.get(exercise, 0)
    total += marks
    print(f"{exercise:>8}   {marks:>2}/10")
print("-" * 16)
print(f"TOTAL: {total}/100")

Exercise   Marks
       1   10/10
       2   10/10
       3   10/10
       4   10/10
       5   10/10
       6   10/10
       7   10/10
       8   10/10
       9   10/10
      10   10/10
----------------
TOTAL: 100/100
